FROM node:22-alpine
RUN apk update && apk upgrade --no-cache libssl3 libcrypto3
RUN npm install -g npm@latest
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=optional
COPY . .
USER node
EXPOSE 5000
CMD ["npm", "run", "dev"]